all:
	@$(MAKE) -C libwasher --no-print-directory
	@$(MAKE) -C washer --no-print-directory
	@$(MAKE) -C drier --no-print-directory

clean:
	rm -f */*.o */*.so libwasher/libwasher washer/washer drier/drier
